/*!
 * Symfony2 template Gruntfile
 * http://marenkay.com/
 * @author Daniel S. Reichenbach
 */

'use strict';

/**
 * Grunt Module
 */
module.exports = function (grunt) {
    /**
     * Configuration
     */
    grunt.initConfig({
        /**
         * Get package meta data
         */
        pkg: grunt.file.readJSON('package.json'),
        /**
         * Get Bower configuration
         */
        bower: grunt.file.readJSON('./.bowerrc'),
        /**
         * Set project object
         */
        project: {
            assets: 'app/Resources/assets',
            css: 'web/css',
            js: 'web/js',
            fonts: 'web/fonts'
        },
        /**
         * Project banner
         */
        tag: {
            banner: '/*! <%= pkg.name %> - version <%= pkg.version %> */\n',
            footer: '/*! Generated by GruntJS on ' +
            '<%= grunt.template.today("yyyy-mm-dd hh:mm") %> */\n'
        },
        /**
         * Copy files from bower packages
         *
         * @see https://www.npmjs.com/package/grunt-contrib-copy
         */
        copy: {
            fonts: {
                files: [
                    {
                        expand: true,
                        cwd: '<%= bower.directory %>/fontface-source-sans-pro/fonts',
                        src: ['EOT/*', 'OTF/*', 'TTF/*', 'WOFF/*'],
                        dest: '<%= project.fonts %>',
                        options: {
                            mode: '0644'
                        }
                    },
                    {
                        expand: true,
                        cwd: '<%= bower.directory %>/foundation-icon-fonts',
                        src: ['*.eot', '*.svg', '*.ttf', '*.woff'],
                        dest: '<%= project.fonts %>',
                        options: {
                            mode: '0644'
                        }
                    }
                ]
            }
        },
        /**
         * Concatenate generated CSS and JS
         *
         * @see https://www.npmjs.com/package/grunt-contrib-concat
         */
        concat: {
            options: {
                stripBanners: true,
                sourceMap: true,
                banner: '<%= tag.banner %>',
                footer: '<%= tag.footer %>'
            },
            vendor: {
                src: [
                    '<%= bower.directory %>/jquery/dist/jquery.js',
                    '<%= bower.directory %>/modernizr/modernizr.js',
                    '<%= bower.directory %>/fastclick/lib/fastclick.js',
                    '<%= bower.directory %>/jquery.cookie/jquery.cookie.js',
                    '<%= bower.directory %>/jquery-placeholder/jquery.placeholder.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.abide.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.accordion.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.alert.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.clearing.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.dropdown.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.interchange.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.joyride.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.magellan.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.offcanvas.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.orbit.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.reveal.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.slider.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.tab.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.tooltip.js',
                    '<%= bower.directory %>/foundation/js/foundation/foundation.topbar.js'
                ],
                dest: '<%= project.js %>/vendor.js',
                nonull: true
            },
            app: {
                src: [
                    '<%= project.assets %>/js/app.main.js'
                ],
                dest: '<%= project.js %>/app.js',
                nonull: true
            }
        },
        /**
         * Compile SCSS to CSS
         *
         * @see https://www.npmjs.com/package/grunt-sass
         */
        sass: {
            options: {
                sourceMap: true
            },
            app: {
                files: {
                    '<%= project.css %>/app.css': '<%= project.assets %>/sass/app.scss'
                }
            }
        },
        /**
         * Add CSS prefixes to generated files
         *
         * @see https://www.npmjs.com/package/grunt-autoprefixer
         */
        autoprefixer: {
            options: {
                map: true
            },
            app: {
                src: '<%= project.css %>/app.css'
            }
        },
        /**
         * Minify generated scripts
         *
         * @see https://www.npmjs.com/package/grunt-contrib-uglify
         */
        uglify: {
            options: {
                compress: {
                    drop_console: true
                },
                sourceMap: true,
                mangle: false
            },
            vendor: {
                files: {
                    '<%= project.js %>/vendor.min.js': '<%= project.js %>/vendor.js'
                }
            },
            app: {
                files: {
                    '<%= project.js %>/app.min.js': '<%= project.js %>/app.js'
                }
            }
        },
        /**
         * Minify generated CSS
         *
         * @see https://www.npmjs.com/package/grunt-contrib-cssmin
         */
        cssmin: {
            options: {},
            app: {
                files: {
                    '<%= project.css %>/app.min.css': '<%= project.css %>/app.css'
                }
            }
        },
        /**
         * Wipe away the generated files
         *
         * @see https://www.npmjs.com/package/grunt-contrib-clean
         */
        clean: {
            release: ['<%= project.css %>', '<%= project.js %>', '<%= project.fonts %>']
        },
        /**
         * Watch Scss and scripts for modifications
         *
         * @see https://www.npmjs.com/package/grunt-contrib-watch
         */
        watch: {
            scripts: {
                files: [
                    '<%= project.assets %>/js/app.main.js'
                ],
                tasks: ['concat']
            },
            sass: {
                files: [
                    '<%= project.assets %>/sass/app.scss'
                ],
                tasks: ['sass']
            }
        }
    });

    /**
     * Load Grunt plugins
     */
    grunt.loadNpmTasks('grunt-autoprefixer');
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-sass');

    /**
     * Default task
     * Run `grunt` on the command line
     */
    grunt.registerTask('default', [
        'clean', 'concat', 'sass', 'autoprefixer', 'uglify', 'cssmin', 'copy'
    ]);
};
