/*!
 * Symfony2 template Gruntfile
 * http://marenkay.com/
 * @author Daniel S. Reichenbach
 */

'use strict';

/**
 * Grunt Module
 */
module.exports = function (grunt) {
    /**
     * Configuration
     */
    grunt.initConfig({
        /**
         * Get package meta data
         */
        pkg: grunt.file.readJSON('package.json'),
        /**
         * Set project object
         */
        project: {
            assets: 'app/Resources/assets',
            css: 'web/css',
            js: 'web/js'
        },
        /**
         * Project banner
         */
        tag: {
          banner: '/*! <%= pkg.name %> - version <%= pkg.version %> */\n',
          footer: '/*! Generated by GruntJS on ' +
                  '<%= grunt.template.today("yyyy-mm-dd hh:mm") %> */\n'
        },
        /**
         * Concatenate generated CSS and JS
         *
         * @see https://www.npmjs.com/package/grunt-contrib-concat
         */
         concat: {
            options: {
                stripBanners: true,
                sourceMap: true,
                banner: '<%= tag.banner %>',
                footer: '<%= tag.footer %>'
            },
            vendor: {
                src: [
                    '<%= project.assets %>/js/vendor/*.js'
                ],
                dest: '<%= project.js %>/vendor.js',
                nonull: true
            },
            app: {
                src: [
                    '<%= project.assets %>/js/app.*.js'
                ],
                dest: '<%= project.js %>/app.js',
                nonull: true
            }
         },
        /**
         * Compile SCSS to CSS
         *
         * @see https://www.npmjs.com/package/grunt-sass
         */
         sass: {
            options: {
                sourceMap: true
            },
            app: {
                files: {
                    '<%= project.css %>/app.css': '<%= project.assets %>/sass/app.scss'
                }
            }
         },
        /**
         * Add CSS prefixes to generated files
         *
         * @see https://www.npmjs.com/package/grunt-autoprefixer
         */
        autoprefixer: {
            options: {
                map: true
            },
            app: {
                src: '<%= project.css %>/app.css'
            }
        },
        /**
         * Minify generated scripts
         *
         * @see https://www.npmjs.com/package/grunt-contrib-uglify
         */
        uglify: {
            options: {
                compress: {
                    drop_console: true
                },
                sourceMap: true,
                mangle: false
            },
            vendor: {
                files: {
                    '<%= project.js %>/vendor.min.js': '<%= project.js %>/vendor.js'
                }
            },
            app: {
                files: {
                    '<%= project.js %>/app.min.js': '<%= project.js %>/app.js'
                }
            }
        },
        /**
         * Minify generated CSS
         *
         * @see https://www.npmjs.com/package/grunt-contrib-cssmin
         */
        cssmin: {
            options: {},
            app: {
                files: {
                    '<%= project.css %>/app.min.css': '<%= project.css %>/app.css'
                }
            }
        },
        /**
         * Wipe away the generated files
         *
         * @see https://www.npmjs.com/package/grunt-contrib-clean
         */
        clean: {
            release: ['<%= project.css %>', '<%= project.js %>']
        },
        /**
         * Watch Scss and scripts for modifications
         *
         * @see https://www.npmjs.com/package/grunt-contrib-watch
         */
         watch: {
            scripts: {
                files: [
                    '<%= project.assets %>/js/vendor/*.js',
                    '<%= project.assets %>/js/app.*.js'
                ],
                tasks: ['concat']
            },
            sass: {
                files: [
                    '<%= project.assets %>/sass/app.scss'
                ],
                tasks: ['sass']
            }
         }
    });

    /**
     * Load Grunt plugins
     */
    grunt.loadNpmTasks('grunt-autoprefixer');
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-sass');

    /**
     * Default task
     * Run `grunt` on the command line
     */
    grunt.registerTask('default', [
        'clean', 'concat', 'sass', 'autoprefixer', 'uglify', 'cssmin'
    ]);
};
