imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: migrations.yml }
    - { resource: fos.yml }

framework:
    translator:      { fallbacks: ["%app.locale%"] }
    secret:          "%app.secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%app.locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name:        'SF2TEMPLATE'
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AppBundle ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database.host%"
        port:     "%database.port%"
        dbname:   "%database.name%"
        user:     "%database.user%"
        password: "%database.password%"
        charset:  "%database.charset%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer.transport%"
    host:      "%mailer.host%"
    port:      "%mailer.port%"
    username:  "%mailer.user%"
    password:  "%mailer.password%"
    spool:     { type: memory }

# AppBundle configuration
app:
    maintenance:
        opcache:
            secret:     "%app.secret%"
            host_ip:    127.0.0.1:80
            host_name:  symfony2-template.dev
            web_dir:    "%kernel.root_dir%/../web"
            protocol:   http
    request_context:
        host:           symfony2-template.dev
        scheme:         http
