# UserBundle configuration
fos_user:
    db_driver:        orm
    firewall_name:    default
    user_class:       AppBundle\Entity\User
    group:
        group_class:  AppBundle\Entity\Group
    service:
        mailer:       fos_user.mailer.twig_swift
