# UserBundle configuration
fos_user:
    db_driver:          orm
    firewall_name:      default
    user_class:         AppBundle\Entity\User
    group:
        group_class:    AppBundle\Entity\Group
    service:
        mailer:         fos_user.mailer.twig_swift
    from_email:
        address:        "%app.mail.address%"
        sender_name:    "%app.mail.sender_name%"
    registration:
        confirmation:
            enabled:    true
        form:
            type:       app_user_registration
            validation_groups:  [Registration, Default, AppRegistration]
    profile:
        form:
            validation_groups:  [Profile, Default, AppProfile]
