# Learn more about services, parameters and containers at
# http://symfony.com/doc/2.7/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.listener.user.events:
        class: AppBundle\EventListener\UserEventListener
        arguments: [ '@doctrine.orm.entity_manager', '@service_container' ]
        tags:
            - { name: kernel.event_subscriber }

    app.listener.session.user.locale:
        class: AppBundle\EventListener\UserLocaleListener
        arguments: [ '@session' ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    app.listener.request.locale:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    app.service.user:
        class: AppBundle\Service\UserManager
        arguments: [ '@doctrine.orm.entity_manager', '@service_container' ]
