# Learn more about services, parameters and containers at
# http://symfony.com/doc/2.7/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.user.events:
        class: AppBundle\EventListener\UserEventListener
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: kernel.event_subscriber }
