# Learn more about services, parameters and containers at
# http://symfony.com/doc/2.7/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.listener.user.events:
        class: AppBundle\EventListener\UserEventListener
        arguments: [ '@doctrine.orm.entity_manager', '@service_container' ]
        tags:
            - { name: kernel.event_subscriber }

    app.listener.request.locale:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    app.listener.session.user.locale:
        class: AppBundle\EventListener\UserLocaleListener
        arguments: [ '@session' ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    app.registration.form.type:
        class: AppBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags: [{ name: "form.type", alias: "app_user_registration" }]

    app.invitation.form.type:
        class: AppBundle\Form\Type\InvitationFormType
        arguments: [@app.invitation.form.data_transformer]
        tags: [{ name: "form.type", alias: "app_invitation_type" }]

    app.invitation.form.data_transformer:
        class: AppBundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: [@doctrine.orm.entity_manager]

    app.service.user:
        class: AppBundle\Service\UserManager
        arguments: [ '@doctrine.orm.entity_manager', '@service_container' ]

    app.service.menu:
        class: AppBundle\Menu\MenuBuilder
        arguments: ['@knp_menu.factory', '@security.authorization_checker']

    app.service.menu.user:
        class: Knp\Menu\MenuItem
        factory: [ "@app.service.menu", createUserMenu ]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: user }
